print ("#############################") 
print ("#                           #")
print ("#  Muhammad Ghazi Rakhmadi  #")
print ("#      2410817310009        #")
print ("#                           #")
print ("#############################")